### ISSUE TITLE
dövizli girişlerde default para birimi tl den farklı olduğunda karşılık olarak 1 yerine tl karşılığını alıyor

### ISSUE THREAD

**Issue by mdpinar** [seyhanp/seyhan#9]

**Comment by cengizalcan** [comment]
Mustafa Bey merhaba,
Bu problem çözüldü mü acaba? Dövizli işlemler yapmaya başlanacakta :)

**Comment by mdpinar** [comment]
bu sorun ana parabirimi olarak TL den başka parabirimi kullananlarda oluyor. türkye'den dövizli çalışmak isteyen firmalar sorun yaşamaz. siz sıkıntı yaşıyor musunuz bu konuda?

**Comment by cengizalcan** [comment]
Mustafa Bey merhaba,

Şuana kadar 12 kalem dövizli işlem yaptım ve şuana kadar herhangi bir problem yaşamadım. Github üzerinde görünce sadece ileride bir sorun yaşarmıyım diye endişelenerek yazdım. Cevabınız için teşekkür ederim.

Mustafa Bey Paypal ile bağış butonunuz var mı ? Bu sayede şirketimizden istenilen dönemlerde size ödeme yapmak isteriz.


PardusTrade Support Teamwww.pardustrade.com & www.pardusticaret.cominfo@pardustrade.comTel: +90 532 372 76 70 (Turkey)Tel: +86 156 6957 4796 (China)Tel: +86 159 426 8810 (China)




Date: Mon, 13 Apr 2015 11:10:37 -0700

**Comment by mdpinar** [comment]
merhabalar Cengiz Bey,

>Github üzerinde görünce sadece ileride bir sorun yaşarmıyım diye
endişelenerek yazdım.
dediğim gibi, bu sıkıntı Türkiye' den farklı bir ülkede hesap tutmak
isteyenler için var.

>Paypal ile bağış butonunuz var mı ?
anasayfaya ekledim, Destekleyin kısmında görebilirsiniz.


13 Nisan 2015 21:51 tarihinde cengizalcan <notifications@github.com> yazdı:

> Mustafa Bey merhaba,
>
> Şuana kadar 12 kalem dövizli işlem yaptım ve şuana kadar herhangi bir
> problem yaşamadım. Github üzerinde görünce sadece ileride bir sorun
> yaşarmıyım diye endişelenerek yazdım. Cevabınız için teşekkür ederim.
>
> Mustafa Bey Paypal ile bağış butonunuz var mı ? Bu sayede şirketimizden
> istenilen dönemlerde size ödeme yapmak isteriz.
>
>
> PardusTrade Support Teamwww.pardustrade.com &
> www.pardusticaret.cominfo@pardustrade.comTel: +90 532 372 76 70
> (Turkey)Tel: +86 156 6957 4796 (China)Tel: +86 159 426 8810 (China)
>
>
>
>
> Date: Mon, 13 Apr 2015 11:10:37 -0700
> From: notifications@github.com
> To: seyhan@noreply.github.com
> CC: cengizalcan@outlook.com
> Subject: Re: [seyhan] dövizli girişlerde default para birimi tl den farklı
> olduğunda karşılık olarak 1 yerine tl karşılığını alıyor (#9)
>
> bu sorun ana parabirimi olarak TL den başka parabirimi kullananlarda
> oluyor. türkye'den dövizli çalışmak isteyen firmalar sorun yaşamaz. siz
> sıkıntı yaşıyor musunuz bu konuda?
>
>
> —
> Reply to this email directly or view it on GitHub.
>
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seyhanp/seyhan/issues/9#issuecomment-92458663>.
>



-- 

İyi günler, iyi çalışmalar...

Mustafa DUMLUPINAR

**Comment by cengizalcan** [comment]
Mustafa Bey merhaba,
Evet az önce gördüm. Paypal üzerinden belli periyotlarda bizde ödeme yapmak isteriz.
Saygılarımla,Cengiz ALCAN


PardusTrade Support Teamwww.pardustrade.com & www.pardusticaret.cominfo@pardustrade.comTel: +90 532 372 76 70 (Turkey)Tel: +86 156 6957 4796 (China)Tel: +86 159 426 8810 (China)




Date: Wed, 15 Apr 2015 00:56:00 -0700
